### ISSUE TITLE
Graph DB for 500M vertices and 2Bn edges labelled by 1M indices.

### ISSUE THREAD

**Issue by panicfarm** [jbmusso/awesome-graph#22]
We are looking to use a graph DB. Our data set has about 500M vertices and 2Bn directed edges. Each edge has an index from 0 to 1M (i.e. on average 2000 edges share the same index). We can have parallel edges with different indices. We need to be able to query for a desired index range. Also, each edge has another value attribute, and each vertex has one scalar attribute. We would have to add more vertices and edges as time goes on. We would like to host this on a single server with large memory. 

- Which graph databases would scale for this data set?
- How would you model such a data set in a graph DB? Should it be a one giant graph or maybe a series of 1M sub-graphs (e.g. one graph per each index value)?

**Comment by jbmusso** [comment]
Hi @panicfarm 
I'm afraid but this question is slightly outside of the scope of this repository. I hope you've been able to process your data.
It looks like JanusGraph would have been a good pick but it's hard to say without looking deeply into the requirements and possibly doing some benchmarks.
