### ISSUE TITLE
Terminus DB should make it on this list

### ISSUE THREAD

**Issue by jethronap** [jbmusso/awesome-graph#25]
Hey nice resources collected. Thanks!
I truly believe you should have a look at TerminusDB,

https://github.com/terminusdb/terminusdb

**Comment by luke-feeney** [comment]
I second this suggestion - thou I am biased ;-)

Great list!

**Comment by jbmusso** [comment]
Sounds like a great addition. Added in https://github.com/jbmusso/awesome-graph/pull/27
