### ISSUE TITLE
Add Datalog as a query language

### ISSUE THREAD

**Issue by luke-feeney** [jbmusso/awesome-graph#26]
The group of graph databases that use [datalog](https://en.wikipedia.org/wiki/Datalog) variants as query languages grows everyday - in fact, I would suggest that it is swiftly becoming the dominant query approach in the new generation of graphs dbs. These new superstars all use datalog:

[TerminusDB](https://github.com/terminusdb/terminusdb)
[Grakn](https://github.com/graknlabs/grakn)
[Crux](https://github.com/juxt/crux)

**Comment by jbmusso** [comment]
Thanks - also added in https://github.com/jbmusso/awesome-graph/pull/27
